version: '3'
name: challenge-jbr

services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      retries: 3
      interval: 3s
    ports: # postgres wont be exposed to host machine, only compose network
      - "5432:5432"

  backend-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:pgpass@postgres:5432
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8081/healthcheck | grep 'Healthy'"]
      retries: 3
      interval: 3s
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"

  graphql-api:
    build:
      context: .
      dockerfile: graphql-api/Dockerfile
    environment:
      BACKEND_API_URL: http://backend-api:8081/
    depends_on:
      backend-api:
        condition: service_healthy
    ports:
      - "8080:8080"
